//! The `// @generated by protoc-gen-rust-mcp. DO NOT EDIT.` header every
//! generated file starts with, the counterpart of Go's header in
//! `generateFile` (`cmd/protoc-gen-go-mcp/mcp.go` at commit `9e072f9`).
//!
//! Go's `generateFile` also prints the file's leading *detached* comments
//! (the ones above `syntax = "proto3";`, via `genLeadingComments` and
//! `source_info::leading_detached_comments`/`file_path::SYNTAX` here)
//! before this banner. Wiring that into a real generated file is left to
//! the full codegen in #6, which is the first caller that has a
//! `FileDescriptorProto` to look them up on; `file_header` below only
//! covers the fixed banner and version lines.

use prost_types::compiler::Version;

/// Renders the file header: the `DO NOT EDIT` banner, followed by a
/// `// versions:` block naming this plugin's own version (from
/// `CARGO_PKG_VERSION` via `plugin_version`) and the `protoc` version from
/// the `CodeGeneratorRequest`'s `compiler_version` (or `(unknown)` if
/// `protoc` didn't send one, which only happens when it's run as a library
/// rather than invoked as `protoc` the CLI).
///
/// Each line is independent (no trailing newline), so a caller joins them
/// with whatever its output format uses (e.g. `"\n"` for a plain `.rs`
/// file). A caller that also wants the file's leading detached comments
/// (see the module doc comment above) prepends those lines itself, from
/// `source_info::leading_detached_comments`.
pub fn file_header(plugin_version: &str, compiler_version: Option<&Version>) -> Vec<String> {
    // Both labels are padded to the same width so the version numbers
    // line up in a column, matching Go's generated header.
    let plugin_label = "// - protoc-gen-rust-mcp ";
    let protoc_label = pad_to("// - protoc ", plugin_label.len());

    vec![
        "// @generated by protoc-gen-rust-mcp. DO NOT EDIT.".to_string(),
        "// versions:".to_string(),
        format!("{plugin_label}v{plugin_version}"),
        format!("{protoc_label}{}", protoc_version(compiler_version)),
    ]
}

/// Right-pads `s` with spaces to at least `width` characters (a no-op if
/// `s` is already that long or longer).
fn pad_to(s: &str, width: usize) -> String {
    let mut out = s.to_string();
    while out.len() < width {
        out.push(' ');
    }
    out
}

/// Formats `compiler_version` the way Go's `protocVersion` does:
/// `vMAJOR.MINOR.PATCH` with a `-suffix` if the compiler sent one (for a
/// pre-release build like `29.3-rc1`), or `(unknown)` if `protoc` didn't
/// send a `compiler_version` at all.
fn protoc_version(compiler_version: Option<&Version>) -> String {
    let Some(v) = compiler_version else {
        return "(unknown)".to_string();
    };
    let major = v.major.unwrap_or(0);
    let minor = v.minor.unwrap_or(0);
    let patch = v.patch.unwrap_or(0);
    let suffix = match v.suffix.as_deref() {
        Some(s) if !s.is_empty() => format!("-{s}"),
        _ => String::new(),
    };
    format!("v{major}.{minor}.{patch}{suffix}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_without_compiler_version_says_unknown() {
        let lines = file_header("0.1.0", None);
        assert_eq!(
            lines[0],
            "// @generated by protoc-gen-rust-mcp. DO NOT EDIT."
        );
        assert_eq!(lines[1], "// versions:");
        assert_eq!(lines[2], "// - protoc-gen-rust-mcp v0.1.0");
        assert_eq!(lines[3], "// - protoc              (unknown)");
    }

    #[test]
    fn header_with_compiler_version() {
        let version = Version {
            major: Some(29),
            minor: Some(3),
            patch: Some(0),
            suffix: None,
        };
        let lines = file_header("0.1.0", Some(&version));
        assert_eq!(lines[3], "// - protoc              v29.3.0");
    }

    #[test]
    fn header_with_compiler_version_suffix() {
        let version = Version {
            major: Some(5),
            minor: Some(29),
            patch: Some(3),
            suffix: Some("rc1".to_string()),
        };
        let lines = file_header("0.1.0", Some(&version));
        assert_eq!(lines[3], "// - protoc              v5.29.3-rc1");
    }

    #[test]
    fn protoc_label_lines_up_with_plugin_label() {
        // The two "// - ..." labels pad to the same width, so "v1.2.3" and
        // "(unknown)" start at the same column, matching Go's aligned
        // header (see example_mcp.pb.go in the Go reference repo).
        let lines = file_header("1.2.3", None);
        let plugin_version_col = lines[2].find("v1.2.3").unwrap();
        let protoc_version_col = lines[3].find("(unknown)").unwrap();
        assert_eq!(plugin_version_col, protoc_version_col);
    }
}
